Repository Walkhub/Walkhub-Server, pull requests merged in 2022-02, with the labels that each got.

#112 🔀 :: (#109) 알림읽음여부 API
  src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationList.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationListId.java
  src/main/java/com/walkhub/walkhub/domain/notification/exception/NotificationNotFoundException.java
  src/main/java/com/walkhub/walkhub/domain/notification/presentation/NotificationController.java
  src/main/java/com/walkhub/walkhub/domain/notification/service/NotificationReadService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가

#195 🔀 :: (#193) SchoolRankJob 수정
  src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRankInfo.java
  src/main/java/com/walkhub/walkhub/domain/rank/job/SchoolRankJob.java
Labels: chore

#197 🔀 :: (#196) DS_STORE .gitignore 추가
  .gitignore
Labels: 프로젝트 설정

#200 🔀 :: (#199) Socket 설정
  build.gradle
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
  src/main/java/com/walkhub/walkhub/global/websocket/SocketRunner.java
  src/main/java/com/walkhub/walkhub/global/websocket/WebSocketConfig.java
  src/main/java/com/walkhub/walkhub/global/websocket/exception/SocketExceptionListener.java
  src/main/java/com/walkhub/walkhub/global/websocket/property/SocketProperty.java
  src/main/resources/application.yml
Labels: 프로젝트 설정

#207 🔀 :: (#205) Socket.io Jwt 설정
  src/main/java/com/walkhub/walkhub/global/websocket/WebSocketConfig.java
  src/main/java/com/walkhub/walkhub/global/websocket/connect/WebSocketJwtHandler.java
  src/main/java/com/walkhub/walkhub/global/websocket/property/ClientProperty.java
Labels: 기능 추가

#206 🔀 :: (#204) default 이미지 설정
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
  src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/Badge.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/infrastructure/image/DefaultImage.java
Labels: chore

#203 🔀 :: (#202) 유저 dto 리팩토링
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/QueryMyPageResponse.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/QueryUserProfileResponse.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java
Labels: 리팩토링

#213 🔀 :: (#211) String -> LocalDate로 변경
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdateUserInfoRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserSignUpRequest.java
Labels: chore

#222 🔀 :: (#220) exception filter 추가
  src/main/java/com/walkhub/walkhub/global/error/ErrorResponse.java
  src/main/java/com/walkhub/walkhub/global/error/ExceptionFilter.java
  src/main/java/com/walkhub/walkhub/global/error/GlobalExceptionHandler.java
  src/main/java/com/walkhub/walkhub/global/security/FilterConfig.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
  src/main/java/com/walkhub/walkhub/global/websocket/exception/SocketExceptionListener.java
Labels: 프로젝트 설정

#221 🔀 :: (#219) birthday 삭제
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdateUserInfoRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserSignUpRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/InputHealthInformationService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
Labels: chore

#177 🔀 :: (#175) 참여한 챌린지 목록 보기 api
  src/main/java/com/walkhub/walkhub/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeDetailService.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryParticipatedChallengeListService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
Labels: 기능 추가

#218 🔀 :: (#217) search school
  src/main/java/com/walkhub/walkhub/domain/school/domain/repository/SchoolRepository.java
  src/main/java/com/walkhub/walkhub/domain/school/presentation/SchoolController.java
  src/main/java/com/walkhub/walkhub/domain/school/presentation/dto/response/SearchSchoolListResponse.java
  src/main/java/com/walkhub/walkhub/domain/school/service/SearchSchoolService.java
Labels: 기능 추가

#216 🔀 :: (#214) accountId 자리수 제한 추가
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserSignUpRequest.java
Labels: chore

#215 🔀 :: (#208) cheering api
  src/main/java/com/walkhub/walkhub/domain/cheering/exception/CanNotCheerMyselfException.java
  src/main/java/com/walkhub/walkhub/domain/cheering/exception/SocketClientNotFoundException.java
  src/main/java/com/walkhub/walkhub/domain/cheering/presentation/CheerController.java
  src/main/java/com/walkhub/walkhub/domain/cheering/presentation/dto/request/CheerRequest.java
  src/main/java/com/walkhub/walkhub/domain/cheering/presentation/dto/response/CheeringMessage.java
  src/main/java/com/walkhub/walkhub/domain/cheering/service/CheeringService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
  src/main/java/com/walkhub/walkhub/global/websocket/connect/WebSocketJwtHandler.java
  src/main/java/com/walkhub/walkhub/global/websocket/exception/SocketExceptionListener.java
Labels: 기능 추가

#224 🔀 :: (#223) 챌린지 비즈니스로직 삭제
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/ChallengeStatus.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepository.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepository.java
  src/main/java/com/walkhub/walkhub/domain/challenge/facade/ChallengeFacade.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presentation/dto/request/CreateChallengeRequest.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presentation/dto/response/ChallengeParticipantsListResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presentation/dto/response/QueryChallengeDetailResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presentation/dto/response/QueryChallengeListResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/CreateChallengeService.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/ParticipateChallengeService.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeDetailService.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeListService.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeParticipantsListService.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryParticipatedChallengeListService.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
Labels: 리팩토링

#225 🔀 :: (#149) Security 설정 오류
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 버그

#227 🔀 :: (#210) @RequestMapping 추가
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/AuthController.java
Labels: 버그

#228 🔀 :: (#226) 선생님 인증코드 수정 api
  src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
  src/main/java/com/walkhub/walkhub/domain/teacher/domain/TeacherAuthCode.java
  src/main/java/com/walkhub/walkhub/domain/teacher/domain/repository/TeacherAuthCodeRepository.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/VerificationCodeService.java
Labels: chore, 리팩토링

#234 🔀 :: (#232) @Column(columnDefinition = "TINYINT") 추가
  src/main/java/com/walkhub/walkhub/domain/user/domain/GroupId.java
Labels: chore

#231 🔀 :: (#72) ExerciseAnalysis 저장 api
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/ExerciseAnalysis.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseAnalysisRepository.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/SaveExerciseAnalysisRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/SaveOrUpdateExerciseAnalysisService.java
Labels: 기능 추가

#235 🔀 :: (#233) 반코드 재발급 api
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/ClassCodeResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/CreateClassService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/RefreshClassCodeService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/Group.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 기능 추가

#101 🔀 :: (#75) 대표뱃지 설정 api
  src/main/java/com/walkhub/walkhub/domain/user/domain/BadgeCollection.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/exception/BadgeNotFoundException.java
  src/main/java/com/walkhub/walkhub/domain/user/facade/BadgeFacade.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/service/TitleBadgeSettingService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가, 리팩토링

#230 🔀 :: (#229) add user number
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/exception/ClassCodeNotMatchException.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/JoinGroupRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/JoinGroupService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가, chore

#237 🔀 :: (#236) erd에 따라 Entity 수정
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
  src/main/java/com/walkhub/walkhub/domain/notice/domain/Notice.java
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/NoticeController.java
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/request/CreateNoticeRequest.java
  src/main/java/com/walkhub/walkhub/domain/notice/service/DeleteNoticeService.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationEntity.java
  src/main/java/com/walkhub/walkhub/domain/notification/presentation/NotificationController.java
  src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
  src/main/java/com/walkhub/walkhub/domain/school/domain/repository/SchoolRepository.java
  src/main/java/com/walkhub/walkhub/domain/school/service/SchoolLogoSettingService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/ClassCodeResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/CodeResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/CreateClassService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/DeleteClassService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/RefreshClassCodeService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/VerificationCodeService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/Group.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/GroupId.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/UserAuthCode.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/GroupRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/facade/UserFacade.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/InputHealthInformationRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserSignUpRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/JoinGroupService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UpdateSchoolInfoService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
Labels: 기능 추가, chore

#241 🔀 :: (#240) cheering add cheeringcount
  src/main/java/com/walkhub/walkhub/domain/cheering/exception/UserNotExercisingException.java
  src/main/java/com/walkhub/walkhub/domain/cheering/service/CheeringService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseRepository.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가

#243 🔀 :: (#242) agencycode groupid
  src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
  src/main/java/com/walkhub/walkhub/domain/school/domain/repository/SchoolRepository.java
  src/main/java/com/walkhub/walkhub/domain/school/presentation/SchoolController.java
  src/main/java/com/walkhub/walkhub/domain/school/presentation/dto/response/SearchSchoolListResponse.java
  src/main/java/com/walkhub/walkhub/domain/school/service/SchoolLogoSettingService.java
  src/main/java/com/walkhub/walkhub/domain/school/service/SearchSchoolService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/DeleteClassService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/GroupRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/facade/GroupFacade.java
  src/main/java/com/walkhub/walkhub/domain/user/facade/UserFacade.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdateSchoolInfoRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserSignUpRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/JoinGroupService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UpdateSchoolInfoService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
Labels: 기능 추가, chore

#247 🔀 :: (#246) BaseTimeEntity 추가
  src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/Badge.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/Group.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
Labels: 기능 추가, chore

#245 🔀 :: (#244) 타입이나 범위에 대한 코드 변경
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/type/GoalType.java
  src/main/java/com/walkhub/walkhub/domain/notice/domain/Notice.java
  src/main/java/com/walkhub/walkhub/domain/notice/domain/type/Scope.java
  src/main/java/com/walkhub/walkhub/domain/notice/service/CreateNoticeService.java
  src/main/java/com/walkhub/walkhub/domain/notice/service/QueryNoticeListService.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationEntity.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/type/Type.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/UserSearchService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/DeleteClassService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/type/Sex.java
  src/main/java/com/walkhub/walkhub/global/enums/Authority.java
  src/main/java/com/walkhub/walkhub/global/enums/Scope.java
Labels: chore

#239 🔀 :: (#238) 타이틀 뱃지 api 변경
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/BadgeCollectionRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/facade/BadgeCollectionFacade.java
  src/main/java/com/walkhub/walkhub/domain/user/facade/BadgeFacade.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/service/TitleBadgeSettingService.java
Labels: 리팩토링

#249 🔀 :: (#248) challenge entity 리팩토링
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/ChallengeStatus.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/type/GoalScope.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationEntity.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/UserSearchService.java
  src/main/java/com/walkhub/walkhub/global/enums/Scope.java
  src/main/java/com/walkhub/walkhub/global/enums/UserScope.java
  src/main/java/com/walkhub/walkhub/infrastructure/fcm/dto/SendDto.java
Labels: 리팩토링

#252 🔀 :: (#251) challenge 엔티티 다시 수정
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
Labels: 리팩토링

#254 🔀 :: (#253) 뱃지 api 분리
  src/main/java/com/walkhub/walkhub/domain/badge/domain/Badge.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/BadgeCollection.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/BadgeCollectionId.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/BadgeCollectionRepository.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/BadgeRepository.java
  src/main/java/com/walkhub/walkhub/domain/badge/exception/BadgeNotFoundException.java
  src/main/java/com/walkhub/walkhub/domain/badge/facade/BadgeCollectionFacade.java
  src/main/java/com/walkhub/walkhub/domain/badge/presentation/BadgeController.java
  src/main/java/com/walkhub/walkhub/domain/badge/service/SetTitleBadgeService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java
Labels: 리팩토링

#257 🔀 :: (#255) Redis 설정
  build.gradle
  src/main/java/com/walkhub/walkhub/global/redis/EmbeddedRedisConfig.java
  src/main/java/com/walkhub/walkhub/global/redis/RedisConfig.java
  src/main/java/com/walkhub/walkhub/global/redis/properties/RedisProperties.java
Labels: 기능 추가

#260 🔀 :: (#258) 챌린지 삭제 API
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
  src/main/java/com/walkhub/walkhub/domain/challenge/facade/ChallengeFacade.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/RemoveChallengeService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가

#262 🔀 :: (#259) Class QueryDeatils
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/DetailsClassResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/QueryStudentCodeService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
  src/main/java/com/walkhub/walkhub/global/enums/Authority.java
Labels: 기능 추가

#271 🔀 :: (#269) show school
  src/main/java/com/walkhub/walkhub/domain/school/domain/repository/SchoolRepository.java
  src/main/java/com/walkhub/walkhub/domain/su/presentation/SuController.java
  src/main/java/com/walkhub/walkhub/domain/su/presentation/dto/response/SchoolListResponse.java
  src/main/java/com/walkhub/walkhub/domain/su/service/ShowSchoolService.java
Labels: 기능 추가

#270 🔀 :: (#268) 하루 목표 걸음수 변경 API
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdateGoalWalkCountRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UpdateGoalWalkCountService.java
Labels: 기능 추가

#279 🔀 :: (#278) 챌린지 목록 조회 api
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepository.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeListResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeListService.java
Labels: 기능 추가

#280 🔀 :: (#277) create challenge
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/request/CreateChallengeRequest.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/CreateChallengeService.java
Labels: 기능 추가

#287 🔀 :: (#285) DDL 오류 해결
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepository.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeListService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/Location.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/LocationId.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/LocationRepository.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/SaveLocationRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseListService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/SaveLocationService.java
  src/main/java/com/walkhub/walkhub/domain/notice/service/CreateNoticeService.java
  src/main/java/com/walkhub/walkhub/domain/notice/service/QueryNoticeListService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/CreateClassService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/DeleteClassService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/QueryStudentCodeService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/RefreshClassCodeService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/Section.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/GroupRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/SectionRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/exception/SectionNotFoundException.java
  src/main/java/com/walkhub/walkhub/domain/user/facade/GroupFacade.java
  src/main/java/com/walkhub/walkhub/domain/user/facade/SectionFacade.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/JoinSectionRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/JoinSectionService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
  src/main/java/com/walkhub/walkhub/infrastructure/image/DefaultImage.java
  src/main/resources/application.yml
Labels: 버그

#293 🔀 :: (#292) add authority
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserTokenResponse.java
  src/main/java/com/walkhub/walkhub/domain/auth/service/UserSignInService.java
Labels: chore

#291 🔀 :: (#256) Redis Cache용 Repository 추가
  build.gradle
  src/main/java/com/walkhub/walkhub/domain/exercise/cache/ExerciseAnalysisCacheRepository.java
  src/main/java/com/walkhub/walkhub/domain/exercise/cache/ExerciseAnalysisCacheRepositoryImpl.java
  src/main/java/com/walkhub/walkhub/domain/exercise/exception/ExerciseAnalysisNotFoundException.java
  src/main/java/com/walkhub/walkhub/domain/exercise/exception/RedisTransactionException.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가

#263 🔀 :: (#261) security authority 세팅
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 리팩토링

#296 🔀 :: (#295) redis error 해결
  build.gradle
Labels: 버그

#282 🔀 :: (#281) 챌린지 상세보기 api
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepository.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeDetailsResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeDetailsService.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeListService.java
Labels: 기능 추가

#305 🔀 :; (#304) delete teacher scope
  src/main/java/com/walkhub/walkhub/domain/notice/domain/type/Scope.java
  src/main/java/com/walkhub/walkhub/domain/notice/service/CreateNoticeService.java
  src/main/java/com/walkhub/walkhub/domain/notice/service/QueryNoticeListService.java
Labels: chore

#301 🔀 :: (#288) 챌린지 참여 API
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepository.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/ParticipateChallengeService.java
Labels: 기능 추가

#299 🔀 :: (#289) show calorie level
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/CalorieLevelRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/CalorieLevelListResponse.java
  src/main/java/com/walkhub/walkhub/domain/user/service/CalorieLevelListService.java
Labels: 기능 추가

#323 🔀 :: (#322) 2차 캐시 설정
  build.gradle
  src/main/java/com/walkhub/walkhub/WalkhubApplication.java
  src/main/resources/application.yml
  src/main/resources/ehcache.xml
Labels: 프로젝트 설정

#318 🔀 :: (#198) SchoolRankJob 변경
  src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRank.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRankId.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRankInfo.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankInfoRepository.java
  src/main/java/com/walkhub/walkhub/domain/rank/job/SchoolRankJob.java
  src/main/java/com/walkhub/walkhub/domain/rank/job/constant/RankJobConstant.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/SchoolRankInfo.java
  src/main/java/com/walkhub/walkhub/domain/rank/scheduler/SchoolRankScheduler.java
  src/main/java/com/walkhub/walkhub/domain/rank/scheduler/UserRankScheduler.java
Labels: 기능 추가

#327 🔀 :: (#326) send claim badge
  src/main/java/com/walkhub/walkhub/domain/badge/domain/Badge.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/BadgeRepository.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/CustomBadgeRepository.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/CustomBadgeRepositoryImpl.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/vo/ClaimBadgeVO.java
  src/main/java/com/walkhub/walkhub/domain/badge/presentation/BadgeController.java
  src/main/java/com/walkhub/walkhub/domain/badge/presentation/dto/response/ClaimBadgeResponse.java
  src/main/java/com/walkhub/walkhub/domain/badge/service/ClaimBadgeService.java
Labels: 기능 추가

#310 🔀 :: (#309) 선생님 인증코드 확인 api
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/request/TeacherCodeRequest.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/ConfirmTeacherCodeService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
  src/main/java/com/walkhub/walkhub/global/exception/InvalidVerificationCodeException.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 기능 추가

#339 🔀 :: (#338) create root account
  src/main/java/com/walkhub/walkhub/domain/school/facade/SchoolFacade.java
  src/main/java/com/walkhub/walkhub/domain/su/presentation/SuController.java
  src/main/java/com/walkhub/walkhub/domain/su/presentation/dto/response/CreateRootAccountResponse.java
  src/main/java/com/walkhub/walkhub/domain/su/service/CreateRootAccountService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 기능 추가

#311 🔀 :: (#290) 챌린지 참여자 목록 조회 API
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepository.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/CustomChallengeRepository.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/CustomChallengeRepositoryImpl.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/vo/ChallengeParticipantsVO.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/type/SuccessScope.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/request/CreateChallengeRequest.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/request/UpdateChallengeRequest.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeDetailsResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeListResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeParticipantsForTeacherResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeParticipantsForTeacherService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
Labels: 기능 추가

#337 🔀 :: (#335) 칼로리 최대 레벨 설정 API
  src/main/java/com/walkhub/walkhub/domain/calorielevel/domain/CalorieLevel.java
  src/main/java/com/walkhub/walkhub/domain/calorielevel/domain/repository/CalorieLevelRepository.java
  src/main/java/com/walkhub/walkhub/domain/calorielevel/exception/CalorieLevelNotFoundException.java
  src/main/java/com/walkhub/walkhub/domain/calorielevel/presentation/CalorieLevelController.java
  src/main/java/com/walkhub/walkhub/domain/calorielevel/service/CalorieLevelListService.java
  src/main/java/com/walkhub/walkhub/domain/calorielevel/service/UpdateMaxCalorieLevelService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가

#336 🔀 :: (#132) 학교 랭킹 조회
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/type/SchoolDateType.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/SchoolRankResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QuerySchoolRankService.java
Labels: 기능 추가

#302 🔀 :: (#273) 운동 분석 결과 출력 API
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/ExerciseAnalysis.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseAnalysisRepository.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/FinishExerciseRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/SaveExerciseAnalysisRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/QueryExerciseAnalysisResponse.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseAnalysisService.java
Labels: 기능 추가

#314 🔀:: (#307) 유저 뱃지 리스트 조회 API
  src/main/java/com/walkhub/walkhub/domain/badge/domain/Badge.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/BadgeCollectionRepository.java
  src/main/java/com/walkhub/walkhub/domain/badge/presentation/BadgeController.java
  src/main/java/com/walkhub/walkhub/domain/badge/presentation/dto/response/QueryUserBadgeListResponse.java
  src/main/java/com/walkhub/walkhub/domain/badge/service/QueryUserBadgeListService.java
Labels: 기능 추가

#347 🔀 :: (#346) show details class add teacher
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/DetailsClassResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/QueryStudentCodeService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/Section.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
  src/main/java/com/walkhub/walkhub/global/enums/Authority.java
Labels: 기능 추가, chore

#354 🔀 :: (#353) CustomChallengeRepository 이름 변경
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepository.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java
Labels: 리팩토링

#334 🔀 :: (#328) 모든 api 검증 / 수정
  src/main/java/com/walkhub/walkhub/domain/calorielevel/domain/CalorieLevel.java
  src/main/java/com/walkhub/walkhub/domain/calorielevel/service/CalorieLevelListService.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/CreateChallengeService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/ExerciseAnalysis.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/LocationId.java
  src/main/java/com/walkhub/walkhub/domain/exercise/exception/AlreadyExercisingException.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/FinishExerciseRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/SaveExerciseAnalysisRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/CreateExerciseService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/SaveOrUpdateExerciseAnalysisService.java
  src/main/java/com/walkhub/walkhub/domain/notice/domain/Notice.java
  src/main/java/com/walkhub/walkhub/domain/notice/service/CreateNoticeService.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserListResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/UserSearchService.java
  src/main/java/com/walkhub/walkhub/domain/school/presentation/SchoolController.java
  src/main/java/com/walkhub/walkhub/domain/school/service/SchoolLogoSettingService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/DeleteClassService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/DetailsClassService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/RefreshClassCodeService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdateUserInfoRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/CalorieLevelListResponse.java
  src/main/java/com/walkhub/walkhub/domain/user/service/InputHealthInformationService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UpdateGoalWalkCountService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
  src/main/java/com/walkhub/walkhub/global/enums/UserScope.java
  src/main/java/com/walkhub/walkhub/global/error/ExceptionFilter.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
  src/main/java/com/walkhub/walkhub/global/security/jwt/JwtTokenProvider.java
Labels: 버그, chore, 리팩토링

#351 🔀 :: (#349) show class list
  src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/ClassListResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/ClassListService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
Labels: 기능 추가

#343 🔀 :: (#341) 챌린지 성공 횟수 변경
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/ChallengeStatus.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/vo/ChallengeParticipantsVO.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/ParticipateChallengeService.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeParticipantsForTeacherService.java
Labels: 기능 추가, 리팩토링

#355 🔀 :: (#352) 로그인 시 사용자 정보 반환
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserTokenResponse.java
  src/main/java/com/walkhub/walkhub/domain/auth/service/UserSignInService.java
  src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
Labels: chore

#357 🔀 :: (#356) CD 파일 수정
  .github/workflows/CD.yml
Labels: chore

#361 🔀 :: (#360) add details class
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseAnalysisRepository.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/DetailsClassResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/DetailsClassService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/QueryUserDetailsService.java
Labels: chore

#350 🔀 :: (#348) excel 내보내기
  build.gradle
  src/main/java/com/walkhub/walkhub/domain/excel/domain/type/UserType.java
  src/main/java/com/walkhub/walkhub/domain/excel/presentation/ExcelController.java
  src/main/java/com/walkhub/walkhub/domain/excel/presentation/dto/request/PrintExcelRequest.java
  src/main/java/com/walkhub/walkhub/domain/excel/presentation/dto/response/PrintExcelResponse.java
  src/main/java/com/walkhub/walkhub/domain/excel/service/PrintExcelService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseAnalysisRepository.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseAnalysisRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseAnalysisRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 기능 추가

#359 🔀 :: (#358) 반 가입 방식 변경
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/SectionRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/exception/ClassCodeNotMatchException.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/service/JoinSectionService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가

#369 🔀 :: (#362) 403 에러 핸들링
  src/main/java/com/walkhub/walkhub/global/error/CustomAuthenticationEntryPoint.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 기능 추가

#368 🔀 :: (#364) 학교 상세보기 api (정보란)
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
  src/main/java/com/walkhub/walkhub/domain/school/presentation/SchoolController.java
  src/main/java/com/walkhub/walkhub/domain/school/presentation/dto/response/SchoolDetailsInfoResponse.java
  src/main/java/com/walkhub/walkhub/domain/school/service/SchoolDetailsInfoService.java
Labels: 기능 추가, chore

#375 🔀 :: (#374) FutureOrPresent 어노테이션 추가
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/request/CreateChallengeRequest.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/request/UpdateChallengeRequest.java
Labels: chore

#383 🔀 :: (#382) account-id 중복체크 API 추가
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/AuthController.java
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/request/CheckAccountIdRequest.java
  src/main/java/com/walkhub/walkhub/domain/auth/service/CheckAccountIdExistsService.java
Labels: 기능 추가

#367 🔀 :: (#363) School 수정 추가
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepository.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
  src/main/java/com/walkhub/walkhub/domain/school/domain/repository/SchoolRepository.java
  src/main/java/com/walkhub/walkhub/domain/school/facade/SchoolFacade.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/request/UpdateTeacherSchoolRequest.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/UpdateTeacherSchoolService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/Section.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UpdateSchoolInfoService.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 기능 추가, chore

#377 🔀 :: (#376) securityConfig 설정
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 버그

#380 🔀 :: (#365) 종료된 챌린지 목록 API
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryClosesChallengeService.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 기능 추가

#373 🔀 :: (#366) 반 탈퇴 API
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/service/ExitSectionService.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 기능 추가

#385 🔀 :: (#381) 전화번호 인증 API
  src/main/java/com/walkhub/walkhub/domain/auth/exception/PhoneNumberNotFoundException.java
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/AuthController.java
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/request/CheckAuthCodeRequest.java
  src/main/java/com/walkhub/walkhub/domain/auth/service/CheckAuthCodeExistsService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가

#384 🔀 :: (#190) 다른 학교 유저 랭킹 조회하기
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/UserRankRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/UserRankRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/rank/facade/UserRankFacade.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserRankListResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListService.java
Labels: 기능 추가

#392 🔀 :: (#391) class list
  src/main/java/com/walkhub/walkhub/domain/teacher/service/ClassListService.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: chore

#393 🔀 :: (#387) JsonFormat으로 변경
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserAccessTokenResponse.java
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserTokenResponse.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/ExerciseListResponse.java
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/response/QueryNoticeListResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/QueryUserDetailsResponse.java
Labels: 버그

#332 🔀:: (#331) 자기 뱃지 목록 조회 API
  src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/CustomBadgeRepository.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/CustomBadgeRepositoryImpl.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/vo/DefaultBadgeVO.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/vo/MyBadgeVo.java
  src/main/java/com/walkhub/walkhub/domain/badge/presentation/BadgeController.java
  src/main/java/com/walkhub/walkhub/domain/badge/presentation/dto/response/QueryMyBadgeListResponse.java
  src/main/java/com/walkhub/walkhub/domain/badge/service/ClaimBadgeService.java
  src/main/java/com/walkhub/walkhub/domain/badge/service/QueryMyBadgeListService.java
Labels: 기능 추가

#317 🔀 :: (#316) user rank job 리팩토링
  src/main/java/com/walkhub/walkhub/domain/rank/job/UserRankJob.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserRankInfo.java
Labels: 리팩토링

#300 🔀 :: (#272) 유저 전체 리스트
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/request/QueryUserListRequest.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/QueryUserListResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/QueryUserListService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/type/AuthorityScope.java
  src/main/java/com/walkhub/walkhub/domain/teacher/type/SortStandard.java
  src/main/java/com/walkhub/walkhub/domain/teacher/vo/UserListInfoVO.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 기능 추가

#395 🔀 :: (#394) Redis 적용하기
  src/main/java/com/walkhub/walkhub/domain/exercise/cache/ExerciseAnalysisCacheRepository.java
  src/main/java/com/walkhub/walkhub/domain/exercise/cache/ExerciseAnalysisCacheRepositoryImpl.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/SaveOrUpdateExerciseAnalysisService.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/UserSearchService.java
Labels: 기능 추가, chore

#406 🔀 :: (#405) DateFormat 변경
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserAccessTokenResponse.java
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserTokenResponse.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/ExerciseListResponse.java
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/response/QueryNoticeListResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/QueryUserDetailsResponse.java
Labels: 버그

#404 🔀 :: (#403) 반 탈퇴 시 챌린지 탈퇴
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UpdateSchoolInfoService.java
Labels: 버그, 리팩토링

#400 🔀 :: (#399) 회원가입시 기본뱃지 설정, 예약어 변경등
  src/main/java/com/walkhub/walkhub/domain/badge/domain/Badge.java
  src/main/java/com/walkhub/walkhub/domain/badge/service/QueryUserBadgeListService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/exception/DefaultTitleBadgeNotFound.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 버그, 리팩토링

#402 🔀 :: (#401) 공지사항 보기 페이징추가
  src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepository.java
  src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/NoticeController.java
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/response/QueryNoticeListResponse.java
  src/main/java/com/walkhub/walkhub/domain/notice/service/QueryNoticeListService.java
Labels: 기능 추가, 리팩토링

#412 🔀 :: (#411) authenticated() -> hasAuthority("USER")로 수정
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: chore

#398 🔀 :: (#178, #396) 학교검색 api, npe해결
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/SchoolListResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QuerySchoolRankService.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/SchoolSearchService.java
  src/main/java/com/walkhub/walkhub/domain/school/service/SchoolDetailsInfoService.java
Labels: 기능 추가, 버그

#414 🔀 :: (#413) 칼로리 레벨 리스트 securityConfig설정
  src/main/java/com/walkhub/walkhub/domain/calorielevel/service/CalorieLevelListService.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: chore

#410 🔀 :: (#409) 유저 전체 리스트 리팩토링
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java
Labels: 리팩토링

#421 🔀 :: (#420) 반 생성할 때 예외 처리
  src/main/java/com/walkhub/walkhub/domain/teacher/service/CreateClassService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/SectionRepository.java
Labels: chore

#417 🔀 :: (#416) 유저 검색 API (선생님용)
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/request/UserSearchRequest.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/UserSearchForTeacherService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java
Labels: 기능 추가

#423 🔀 :: (#422) AsyncConfigurer를 override하여 asyncExecutor 설정
  src/main/java/com/walkhub/walkhub/global/async/AsyncConfig.java
Labels: chore

#425 🔀 :: (#424) 유저 검색 선생님용 403 해결
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 버그

#427 🔀 :: (#424) 유저 검색 선생님용 버그 재수정
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 버그

#431 🔀 :: (#430) Timezone 설정 추가
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserAccessTokenResponse.java
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserTokenResponse.java
  src/main/java/com/walkhub/walkhub/domain/auth/service/TokenRefreshService.java
  src/main/java/com/walkhub/walkhub/domain/auth/service/UserSignInService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/ExerciseListResponse.java
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/response/QueryNoticeListResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRankId.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/QueryUserDetailsResponse.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
  src/main/java/com/walkhub/walkhub/global/date/DateTimeZoneConfiguration.java
  src/main/java/com/walkhub/walkhub/global/entity/BaseTimeEntity.java
Labels: 버그, chore

#429 🔀 :: (#428) securityConfig 설정 추가
  src/main/java/com/walkhub/walkhub/domain/notice/service/DeleteNoticeService.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 버그

#433 🔀 :: (#432) 선생님 인증 API 수정
  src/main/java/com/walkhub/walkhub/domain/teacher/service/ConfirmTeacherCodeService.java
Labels: chore

#440 🔀 :: (#439) DateTimeFormat 변경
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserAccessTokenResponse.java
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserTokenResponse.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/ExerciseListResponse.java
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/response/QueryNoticeListResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/QueryUserDetailsResponse.java
Labels: 버그

#437 🔀 :: (#436) 운동 기록 상세보기API
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/LocationRepository.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/QueryExerciseDetailsResponse.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseDetailsService.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 기능 추가

#435 🔀 :: (#434) 선생님 목록 API 수정
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/ClassListResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/ClassListService.java
Labels: 기능 추가

#447 🔀 :: (#446) BaseTimeEntity 수정
  src/main/java/com/walkhub/walkhub/global/entity/BaseTimeEntity.java
Labels: 버그

#449 🔀 :: (#448) 오타 수정
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 버그

#445 🔀 :: (#444) Section 목록에서 반 없는 선생님도 보여주도록 변경
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/ClassListResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/ClassListService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
Labels: chore

#419 🔀 :: (#418) 챌린지 참여자 목록 API 추가
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/vo/ChallengeProgressVO.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/type/ChallengeParticipantsOrder.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/type/ChallengeParticipantsScope.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/request/QueryChallengeProgressRequest.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeParticipantsForTeacherResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeProgressResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeParticipantsForTeacherService.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeProgressService.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 기능 추가

#443 🔀 :: (#442) 우리 학교 유저 랭킹 리팩토링
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
Labels: 리팩토링

#441 🔀 :: (#438) user rank job constant로 리팩토링
  src/main/java/com/walkhub/walkhub/domain/rank/domain/UserRank.java
  src/main/java/com/walkhub/walkhub/domain/rank/job/UserRankJob.java
  src/main/java/com/walkhub/walkhub/domain/rank/job/constant/RankJobConstant.java
Labels: 리팩토링

#452 🔀 :: (#451) 유저 랭킹 학년 반 삭제
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/UserRankRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/vo/UserRankVO.java
  src/main/java/com/walkhub/walkhub/domain/rank/facade/UserRankFacade.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserRankListResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
Labels: 리팩토링

#454 🔀 :: (#453) 건강 정보 수정 API 성별 추가
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/InputHealthInformationRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/InputHealthInformationService.java
Labels: 리팩토링

#468 🔀 :: (#467) 임시 로그 설정
  src/main/java/com/walkhub/walkhub/global/websocket/connect/WebSocketJwtHandler.java
Labels: 기능 추가

#464 🔀 :: (#463) 권한 수정
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: chore

#470 🔀 :: (#469) 쿼리 버그 수정
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java
Labels: 버그

#475 🔀 :: (#474) 다른학교 유저 랭킹 dto 분리
  src/main/java/com/walkhub/walkhub/domain/rank/facade/UserRankFacade.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/OtherSchoolUserRankListResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/OurSchoolUserRankListResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListService.java
Labels: chore, 리팩토링

#479 🔀 :: (#476) school rank job 크론 주기
  src/main/java/com/walkhub/walkhub/domain/rank/scheduler/SchoolRankScheduler.java
Labels: chore

#489 🔀 :: (#488) CheeringService log 설정
  src/main/java/com/walkhub/walkhub/domain/cheering/service/CheeringService.java
Labels: 기능 추가
