Repository Walkhub/Walkhub-Server, pull requests merged in 2022-04, with the labels that each got.

#627 🔀 :: (#586) 선생님 관리 API
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/ManageTeachersResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/ManageTeacherService.java
Labels: 기능 추가

#629 🔀 :: (#623) ROOT 계정 비밀번호 관리
  src/main/java/com/walkhub/walkhub/domain/su/presentation/SuController.java
  src/main/java/com/walkhub/walkhub/domain/su/presentation/dto/response/CreateRootAccountResponse.java
  src/main/java/com/walkhub/walkhub/domain/su/presentation/dto/response/RootAccountResponse.java
  src/main/java/com/walkhub/walkhub/domain/su/presentation/dto/response/SchoolListResponse.java
  src/main/java/com/walkhub/walkhub/domain/su/service/CreateRootAccountService.java
  src/main/java/com/walkhub/walkhub/domain/su/service/ShowSchoolService.java
  src/main/java/com/walkhub/walkhub/domain/su/service/UpdateSchoolPasswordService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
Labels: 기능 추가

#626 🔀 :: (#613) 챌린지 참여자 목록 보기 Api
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/vo/ChallengeDetailsForTeacherVO.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/request/ChallengeParticipantRequest.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeParticipantListResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeParticipantListService.java
Labels: 기능 추가, chore

#631 🔀 :: (#628) 유저 상세보기 API
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/QueryUserDetailsResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/QueryUserDetailsService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/UserSearchForTeacherService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/vo/UserDetailsVO.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/vo/UserListInfoVO.java
Labels: chore

#632 🔀 :: (#630) stored procedure 생성 자동화
  src/main/resources/application.yml
  src/main/resources/createProcedures.sql
  src/main/resources/dropProcedures.sql
Labels: 기능 추가

#637 🔀 :: (#636) Response값 userCount -> totalUserCount로 수정
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserRankListResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
  src/main/java/com/walkhub/walkhub/domain/school/service/SchoolDetailsInfoService.java
Labels: chore, 리팩토링

#633 🔀 :: (#624) 학교 랭킹 조회 및 검색 api
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/vo/SchoolListVo.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/type/Scope.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/type/Sort.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/request/SchoolSearchRequest.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/SchoolListResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/SchoolSearchService.java
Labels: 리팩토링

#639 🔀 :: (#638) Head Method Body -> Param으로 변경
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/AuthController.java
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/request/CheckAccountIdRequest.java
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/request/CheckAuthCodeRequest.java
  src/main/java/com/walkhub/walkhub/domain/auth/service/CheckAccountIdExistsService.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/CheckClassCodeRequest.java
  src/main/java/com/walkhub/walkhub/global/error/GlobalExceptionHandler.java
Labels: chore, 리팩토링

#612 🔀 :: (#585) fcm error handling
  src/main/java/com/walkhub/walkhub/domain/notification/domain/type/Type.java
  src/main/java/com/walkhub/walkhub/domain/notification/presentation/NotificationController.java
  src/main/java/com/walkhub/walkhub/domain/notification/presentation/dto/request/SubscribeRequest.java
  src/main/java/com/walkhub/walkhub/infrastructure/fcm/FcmUtil.java
  src/main/java/com/walkhub/walkhub/infrastructure/fcm/FirebaseNotification.java
Labels: 기능 추가, 리팩토링

#643 🔀 :: (#640) create root error
  src/main/java/com/walkhub/walkhub/domain/su/exception/SchoolRootUserExistsException.java
  src/main/java/com/walkhub/walkhub/domain/su/service/CreateRootAccountService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가, 버그

#650 🔀 :: (#649) 전화번호 인증 로직 변경
  src/main/java/com/walkhub/walkhub/domain/auth/service/CheckAuthCodeExistsService.java
Labels: 버그

#654 🔀 :: (#653) test file 삭제
  src/test/java/com/walkhub/walkhub/IntegrationTest.java
Labels: chore

#652 🔀 :: (#651) spring boot 실행 시 procedure 생성 sql 수정
  src/main/resources/createProcedures.sql
Labels: 리팩토링

#656 🔀 :: (#655) 학교 상세보기 Api 수정
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
  src/main/java/com/walkhub/walkhub/domain/school/presentation/dto/response/SchoolDetailsInfoResponse.java
  src/main/java/com/walkhub/walkhub/domain/school/service/SchoolDetailsInfoService.java
Labels: chore, 리팩토링

#648 🔀 :: (#625) 챌린지 목록 보기(웹)
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/vo/ShowChallengeListForTeacherVo.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeListForTeacherResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeListForTeacherService.java
Labels: 기능 추가

#658 🔀 :: (#657) 회원가입 시 전화번호 중복 체크 로직 추가
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가, chore, 리팩토링

#660 🔀 :: (#659) 운동기록 보기(선생님용) Api 수정
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/QueryExerciseHistoryRequest.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 버그, chore, 리팩토링

#662 🔀 :: (#661) 챌린지 상세보기(웹) Api 수정
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeDetailsForTeacherResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeDetailsForTeacherService.java
Labels: chore

#666 🔀 :: (#665) 현재 걸음 수 & 거리 추가
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeDetailsForStudentResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeDetailsForStudentService.java
Labels: 기능 추가, chore

#668 🔀 :: (#667) 챌린지 목록 보기(웹) url 변경
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
Labels: 리팩토링

#670 🔀 :: (#669) Log out API
  src/main/java/com/walkhub/walkhub/domain/auth/domain/repository/RefreshTokenRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/service/LogoutService.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 기능 추가

#674 🔀 :: (#673) dto분리작업
  src/main/java/com/walkhub/walkhub/domain/rank/facade/UserRankFacade.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserRankListByMySchoolResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserRankListResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
Labels: chore

#676 🔀 :: (#675) 내 학교 정보 조회(앱) 변경
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryMySchoolRankService.java
Labels: chore, 리팩토링

#680 🔀 :: (#679) 회원가입 API Request 수정
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserSignUpRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
Labels: chore

#677 🔀 :: (#671) 명세대로 수정
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
  src/main/java/com/walkhub/walkhub/domain/challenge/facade/ChallengeFacade.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/CreateChallengeService.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeDetailsForTeacherService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
Labels: 기능 추가, chore, 리팩토링

#684 🔀 :: (#683) 학교 랭킹 조회 및 검색 Api 수정
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/rank/facade/UserRankFacade.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/request/SchoolSearchRequest.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/SchoolSearchService.java
Labels: chore, 리팩토링

#686 🔀 :: (#685) 챌린지 생성 시 Response값 수정
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/CreateChallengeResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/CreateChallengeService.java
Labels: chore

#688 🔀 :: (#687) userCount 추가
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/DetailsClassResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/DetailsClassService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
Labels: 기능 추가

#693 🔀 :: (#692) scope 추가
  src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/response/QueryNoticeListResponse.java
Labels: 기능 추가, DOCS

#690 🔀 :: (#689) 알림 목록 API 수정
  src/main/java/com/walkhub/walkhub/domain/notification/presentation/dto/response/QueryNotificationListResponse.java
  src/main/java/com/walkhub/walkhub/domain/notification/service/QueryNotificationListService.java
  src/main/java/com/walkhub/walkhub/infrastructure/fcm/FcmUtil.java
  src/main/java/com/walkhub/walkhub/infrastructure/fcm/FirebaseNotification.java
Labels: 기능 추가, chore

#694 🔀 :: (#691) 전체 엔티티에 유니크 제약조건 추가
  src/main/java/com/walkhub/walkhub/domain/badge/domain/Badge.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/BadgeCollection.java
  src/main/java/com/walkhub/walkhub/domain/calorielevel/domain/CalorieLevel.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/ChallengeStatus.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/ChallengeStatusId.java
  src/main/java/com/walkhub/walkhub/domain/exercise/cache/ExerciseAnalysisCacheRepositoryImpl.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/CertifyingShot.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/ExerciseAnalysis.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/Location.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/CertifyingShotRepository.java
  src/main/java/com/walkhub/walkhub/domain/notice/domain/Notice.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationEntity.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationList.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/type/NotificationType.java
  src/main/java/com/walkhub/walkhub/domain/notification/presentation/dto/request/SubscribeRequest.java
  src/main/java/com/walkhub/walkhub/domain/notification/presentation/dto/response/QueryNotificationListResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRank.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRankId.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/UserRank.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/UserRankId.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/vo/SchoolRankWriterVO.java
  src/main/java/com/walkhub/walkhub/domain/rank/job/SchoolRankJob.java
  src/main/java/com/walkhub/walkhub/domain/rank/job/UserRankJob.java
  src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/Section.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/infrastructure/fcm/dto/request/NotificationRequest.java
  src/main/java/com/walkhub/walkhub/infrastructure/image/DefaultImage.java
Labels: chore, 리팩토링

#696 🔀 :: (#695) Refresh Token 발급 시 만료 시간 설정
  src/main/java/com/walkhub/walkhub/domain/auth/domain/RefreshToken.java
  src/main/java/com/walkhub/walkhub/domain/auth/service/TokenRefreshService.java
Labels: chore

#701 🔀 :: (#697) Entity에 Default Value 적용 오류
  src/main/java/com/walkhub/walkhub/domain/badge/domain/Badge.java
  src/main/java/com/walkhub/walkhub/domain/calorielevel/domain/CalorieLevel.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/request/CreateChallengeRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/CreateExerciseRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/CreateExerciseService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/FinishExerciseService.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationList.java
  src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
Labels: 버그
