Repository Walkhub/Walkhub-Server, pull requests merged in 2022-03, with the labels that each got.

#481 🔀 :: (#480) user rank 파라미터 수정
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
Labels: chore

#473 🔀 :: (#472) where문 추가
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java
Labels: 버그

#478 🔀 :: (#477) 챌린지 상세보기 수정
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeDetailsResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeDetailsService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
Labels: chore

#460 🔀 :: (#459) 명세 따라 자잘한 수정
  src/main/java/com/walkhub/walkhub/domain/calorielevel/domain/repository/CalorieLevelRepository.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/CreateExerciseRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/QueryExerciseDetailsResponse.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseDetailsService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
Labels: 버그, chore

#490 🔀 :: (#485) 운동 종료 인증샷
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/CertifyingShot.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/CertifyingShotRepository.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/FinishExerciseRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/FinishExerciseService.java
Labels: chore

#491 🔀 :: (#486) 챌린지 참여 시 NPE
  src/main/java/com/walkhub/walkhub/domain/challenge/service/ParticipateChallengeService.java
Labels: chore

#494 🔀 :: (#493) school_image_url 추가
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/QueryUserProfileResponse.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
Labels: chore

#483 🔀 :: (#482) 운동 중인 유저 리스트 보기 api
  src/main/java/com/walkhub/walkhub/domain/calorielevel/domain/repository/CalorieLevelRepository.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeDetailsResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/ParticipateChallengeService.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeDetailsService.java
  src/main/java/com/walkhub/walkhub/domain/cheering/service/CheeringService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/CertifyingShot.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/CertifyingShotRepository.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseRepository.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/CreateExerciseRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/FinishExerciseRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/QueryExerciseDetailsResponse.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/QueryExercisingUserListResponse.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/CreateExerciseService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseDetailsService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExercisingUserListService.java
  src/main/java/com/walkhub/walkhub/domain/rank/facade/UserRankFacade.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/OtherSchoolUserRankListResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserRankListResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/scheduler/SchoolRankScheduler.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/DeleteClassService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 기능 추가, chore

#504 🔀 :: (#503) 날라간 pr 복구, zonedDateTime 에러
  src/main/java/com/walkhub/walkhub/domain/calorielevel/domain/repository/CalorieLevelRepository.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeDetailsResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeDetailsService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/CreateExerciseRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/QueryExerciseDetailsResponse.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseDetailsService.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRankId.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
Labels: 버그

#345 🔀 :: (#342) fcm topic 형식으로 변경
  .gitignore
  build.gradle
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationEntity.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/type/Type.java
  src/main/java/com/walkhub/walkhub/domain/notification/presentation/NotificationController.java
  src/main/java/com/walkhub/walkhub/domain/notification/presentation/dto/response/QueryNotificationListResponse.java
  src/main/java/com/walkhub/walkhub/domain/notification/service/QueryNotificationListService.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
  src/main/java/com/walkhub/walkhub/infrastructure/fcm/CoolNotification.java
  src/main/java/com/walkhub/walkhub/infrastructure/fcm/FcmUtil.java
  src/main/java/com/walkhub/walkhub/infrastructure/fcm/dto/request/NotificationRequest.java
Labels: 기능 추가, 리팩토링

#509 🔀 :: (#505) /rank api 수정
  src/main/java/com/walkhub/walkhub/domain/rank/service/QuerySchoolRankService.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListService.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/SchoolSearchService.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/UserSearchService.java
Labels: 버그, chore

#510 🔀 :: (#506) 운동 API
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseAnalysisRepository.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/CreateExerciseRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/FinishExerciseService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseAnalysisService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExercisingUserListService.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserRankListResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
Labels: 기능 추가, 리팩토링

#512 🔀 :: (#511) 하루 목표 걸음수 조회 api
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/QueryGoalWalkCountResponse.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryGoalWalkCountService.java
Labels: 기능 추가

#513 🔀 :: (#501) 운동 분석 결과 출력 API
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseAnalysisService.java
Labels: 기능 추가

#516 🔀 :: (#515) QueryExerciseAnalysisList
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseAnalysisService.java
Labels: chore

#518 🔀 :: (#517) 운동한 시간 컬럼
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/QueryExerciseAnalysisResponse.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseAnalysisService.java
Labels: chore

#521 🔀 :; (#520) 반 리스트 보여주기에서 userCount 추가
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/ClassListResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/ClassListService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
Labels: 기능 추가

#523 🔀 :: (#520) school section list
  src/main/java/com/walkhub/walkhub/domain/teacher/service/ClassListService.java
Labels: 기능 추가

#502 🔀 :: (#276) claim badge send
  src/main/java/com/walkhub/walkhub/domain/badge/badges/BadgeFactory.java
  src/main/java/com/walkhub/walkhub/domain/badge/badges/BaseBadge.java
  src/main/java/com/walkhub/walkhub/domain/badge/badges/BetaTesterBadge.java
  src/main/java/com/walkhub/walkhub/domain/badge/badges/Day10000StepsBadge.java
  src/main/java/com/walkhub/walkhub/domain/badge/badges/Day30000StepsBadge.java
  src/main/java/com/walkhub/walkhub/domain/badge/badges/Day50000StepsBadge.java
  src/main/java/com/walkhub/walkhub/domain/badge/badges/FrozenHumanBadge.java
  src/main/java/com/walkhub/walkhub/domain/badge/badges/GoJinHoBadge.java
  src/main/java/com/walkhub/walkhub/domain/badge/badges/GoldShoesBadge.java
  src/main/java/com/walkhub/walkhub/domain/badge/badges/MarathonBadge.java
  src/main/java/com/walkhub/walkhub/domain/badge/badges/SeoulBusanBadge.java
  src/main/java/com/walkhub/walkhub/domain/badge/badges/SliverShoesBadge.java
  src/main/java/com/walkhub/walkhub/domain/badge/badges/StartBadge.java
  src/main/java/com/walkhub/walkhub/domain/badge/badges/UbdBadge.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/Badge.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/BadgeCollectionRepository.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/BadgeRepository.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/CustomBadgeRepositoryImpl.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/vo/DefaultBadgeVO.java
  src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/vo/MyBadgeVo.java
  src/main/java/com/walkhub/walkhub/domain/badge/enums/BadgeType.java
  src/main/java/com/walkhub/walkhub/domain/badge/exception/BadgeTypeNotFoundException.java
  src/main/java/com/walkhub/walkhub/domain/badge/presentation/dto/response/QueryUserBadgeListResponse.java
  src/main/java/com/walkhub/walkhub/domain/badge/service/ClaimBadgeService.java
  src/main/java/com/walkhub/walkhub/domain/badge/service/QueryUserBadgeListService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseAnalysisRepository.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가, chore

#525 🔀 :: (#524) 회원가입 API 리팩토링
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserSignUpRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
Labels: 기능 추가, 리팩토링

#527 🔀 :: (#526) 전화번호 인증 Api 리팩토링
  src/main/java/com/walkhub/walkhub/domain/user/domain/UserAuthCode.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserAuthCodeService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
Labels: 리팩토링

#529 🔀 :: (#528) 토큰 재발급 Api 리팩토링
  src/main/java/com/walkhub/walkhub/domain/auth/domain/RefreshToken.java
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/AuthController.java
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserTokenRefreshResponse.java
  src/main/java/com/walkhub/walkhub/domain/auth/service/TokenRefreshService.java
Labels: 리팩토링

#535 🔀 :: (#534) 획득한 뱃지 보여주기 Api 추가
  src/main/java/com/walkhub/walkhub/domain/badge/badges/BadgeFactory.java
  src/main/java/com/walkhub/walkhub/domain/badge/badges/FirstPlaceBadge.java
  src/main/java/com/walkhub/walkhub/domain/badge/badges/ReceiveBadge.java
  src/main/java/com/walkhub/walkhub/domain/badge/badges/TenFirstPlaceBadge.java
  src/main/java/com/walkhub/walkhub/domain/badge/enums/BadgeType.java
  src/main/java/com/walkhub/walkhub/domain/badge/service/ClaimBadgeService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseRepository.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/UserRankRepository.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/UserSearchService.java
Labels: 기능 추가, chore

#539 🔀 :: (#538) 하루 목표 걸음수 Valid
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
Labels: 리팩토링

#549 🔀 :: (#548) 칼로리 레벨 목록 조회 Api 수정
  src/main/java/com/walkhub/walkhub/domain/calorielevel/domain/repository/CalorieLevelRepository.java
  src/main/java/com/walkhub/walkhub/domain/calorielevel/service/CalorieLevelListService.java
Labels: 기능 추가, 리팩토링

#551 🔀 :: (#550) 공지사항 작성 Api 수정
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/request/CreateNoticeRequest.java
Labels: 리팩토링

#547 🔀 :: (#546) 내 정보 수정 Api 수정
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdateSchoolInfoRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdateUserInfoRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UpdateSchoolInfoService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UpdateUserInfoService.java
Labels: 기능 추가, 리팩토링

#545 🔀 :: (#544) 반 코드 확인 체크 Api
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/SectionRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/exception/InvalidCodeException.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/CheckClassCodeRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/CheckClassCodeService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가

#553 🔀 :: (#552) Challenge 자잘한 수정
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/request/CreateChallengeRequest.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/request/UpdateChallengeRequest.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/RemoveChallengeService.java
Labels: chore

#555 🔀 :: (#554) 챌린지 전체 목록 조회 Api 수정
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/vo/ShowChallengeVO.java
  src/main/java/com/walkhub/walkhub/domain/challenge/facade/ChallengeFacade.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeListResponse.java
Labels: chore, 리팩토링

#557 🔀 :: (#556) fcm exception 처리 변경
  src/main/java/com/walkhub/walkhub/domain/notification/presentation/NotificationController.java
Labels: 리팩토링

#561 🔀 :: (#560) number columnDefinition 수정
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
Labels: 버그, chore

#562 🔀 :: (#558) 변수명 변경, 영속성 컨텍스트 로직 삭제
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
Labels: chore

#564 🔀 :: (#563) 마이페이지 API 수정
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/QueryUserProfileResponse.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java
Labels: chore

#566 🔀 :: (#565) 운동기록 리스트 Api 페이지
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseRepository.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseListService.java
Labels: chore

#571 🔀 :: (#569) 건강정보 수정 if문 삭제
  src/main/java/com/walkhub/walkhub/domain/user/service/InputHealthInformationService.java
Labels: chore

#573 🔀 :: (#572) key값 안넣었을 때 에러 처리
  src/main/java/com/walkhub/walkhub/domain/image/presentation/ImageController.java
Labels: 버그

#576 🔀 :: (#575) 반 상세보기 Response
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/DetailsClassResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/DetailsClassService.java
Labels: 기능 추가

#578 🔀 :: (#577) 공지사항 보기 api
  src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepositoryCustomImpl.java
Labels: chore

#582 🔀 :: (#581) Custom Repository에 @Repository 제거
  src/main/java/com/walkhub/walkhub/domain/badge/domain/repository/CustomBadgeRepositoryImpl.java
  src/main/java/com/walkhub/walkhub/domain/exercise/cache/ExerciseAnalysisCacheRepositoryImpl.java
Labels: chore

#584 🔀 :: (#583) @Repository 어노테이션 추가
  src/main/java/com/walkhub/walkhub/domain/exercise/cache/ExerciseAnalysisCacheRepositoryImpl.java
Labels: 버그

#580 🔀 :: (#579) 운동기록 보기(선생님용) Api
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeProgressService.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryClosesChallengeService.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryParticipatedChallengeListService.java
  src/main/java/com/walkhub/walkhub/domain/cheering/presentation/dto/response/CheeringMessage.java
  src/main/java/com/walkhub/walkhub/domain/cheering/service/CheeringService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseRepository.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/QueryExerciseHistoryRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/QueryExerciseHistoryResponse.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseAnalysisService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseHistoryService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseListService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/vo/ExerciseVO.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/vo/UserRankWriterVO.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/request/UserSearchRequest.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/QueryUserListService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/UserSearchForTeacherService.java
  src/main/java/com/walkhub/walkhub/global/entity/BaseTimeEntity.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
  src/main/java/com/walkhub/walkhub/infrastructure/fcm/dto/request/NotificationInformation.java
Labels: 기능 추가

#605 🔀 :: (#604) CODEWOENRS 변경
  .github/CODEOWNERS
Labels: 프로젝트 설정

#595 🔀 :: (#590) 건강 정보 조회 Api
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/HealthResponse.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserHealthService.java
Labels: 기능 추가

#601 🔀 :: (#598) 위치 가져오기 Api Response 변경
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/QueryExerciseDetailsResponse.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseDetailsService.java
Labels: 기능 추가

#611 🔀 :: (#608) Controller에 추가
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/AuthController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyInformationService.java
Labels: 기능 추가, chore

#603 🔀 :: (#597) 공지사항 수정 API
  src/main/java/com/walkhub/walkhub/domain/notice/domain/Notice.java
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/NoticeController.java
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/request/ModifyNoticeRequest.java
  src/main/java/com/walkhub/walkhub/domain/notice/service/ModifyNoticeService.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 기능 추가

#615 🔀 :: (#614) 유저 검색 선생님용 API 수정
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java
Labels: chore

#619 🔀 :: (#618) NPE 설정
  src/main/java/com/walkhub/walkhub/domain/auth/service/UserSignInService.java
Labels: 버그, chore

#622 🔀 :: (#621) 내 학교 랭킹 조회 API 수정
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/SchoolRankResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryMySchoolRankService.java
Labels: chore

#610 🔀 :: (#600) 내 클래스 조회 Api 추가
  src/main/java/com/walkhub/walkhub/domain/teacher/facade/TeacherFacade.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/ClassListResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/ClassResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/ClassListService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/QueryMyClassService.java
Labels: 기능 추가
