Repository Walkhub/Walkhub-Server, pull requests merged in 2022-01, with the labels that each got.

#7 🔀 :: CODEOWNERS 파일 추가
  .github/CODEOWNERS
Labels: 프로젝트 설정

#5 🔀 :: 프로젝트 구조 설정
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/com/walkhub/walkhub/WalkhubApplication.java
  src/main/java/com/walkhub/walkhub/domain/challenge/.gitkeep
  src/main/java/com/walkhub/walkhub/domain/exercise/.gitkeep
  src/main/java/com/walkhub/walkhub/domain/image/.gitkeep
  src/main/java/com/walkhub/walkhub/domain/notice/.gitkeep
  src/main/java/com/walkhub/walkhub/domain/notification/.gitkeep
  src/main/java/com/walkhub/walkhub/domain/rank/.gitkeep
  src/main/java/com/walkhub/walkhub/domain/teacher/.gitkeep
  src/main/java/com/walkhub/walkhub/domain/user/.gitkeep
  src/main/java/com/walkhub/walkhub/global/error/.gitkeep
  src/main/java/com/walkhub/walkhub/global/security/.gitkeep
  src/main/java/com/walkhub/walkhub/global/web/WebMvcConfig.java
  src/main/java/com/walkhub/walkhub/infrastructure/fcm/.gitkeep
  src/main/java/com/walkhub/walkhub/infrastructure/s3/.gitkeep
  src/main/resources/application.yml
Labels: 프로젝트 설정

#11 🔀 :: (#8) school entity
  build.gradle
  src/main/java/com/walkhub/walkhub/domain/user/entity/School.java
Labels: 기능 추가

#17 🔀 :: (#12) notification entity
  src/main/java/com/walkhub/walkhub/domain/notification/domain/Notification.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/repository/NotificationRepository.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/type/Type.java
  src/main/java/com/walkhub/walkhub/global/enums/Scope.java
Labels: 기능 추가

#19 🔀 :: (#16) School 엔티티 수정
  src/main/java/com/walkhub/walkhub/domain/user/domain/School.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/SchoolRepository.java
Labels: 리팩토링

#31 🔀 :: (#14) badge entity 생성
  src/main/java/com/walkhub/walkhub/domain/user/domain/Badge.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/BadgeRepository.java
Labels: 기능 추가

#34 🔀 :: (#33) 대문자 -> 소문자
  src/main/java/com/walkhub/walkhub/domain/user/domain/Badge.java
Labels: 버그

#30 🔀 :: (#9) group entity
  src/main/java/com/walkhub/walkhub/domain/user/domain/Group.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/GroupId.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/GroupRepository.java
Labels: 기능 추가

#32 🔀 :: (#20) notification_list entity
  src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationList.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationListId.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/repository/NotificationListRepository.java
Labels: 기능 추가

#36 🔀 :: (#21) teacher-auth-code-entity
  build.gradle
  src/main/java/com/walkhub/walkhub/domain/teacher/domain/AuthCode.java
  src/main/java/com/walkhub/walkhub/domain/teacher/domain/repository/AuthCodeRepository.java
Labels: 기능 추가

#37 🔀 :: (#10) user-entity
  build.gradle
  src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationList.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/repository/NotificationRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/BadgeRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/GroupRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/SchoolRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/type/HealthInfo.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/type/Sex.java
  src/main/java/com/walkhub/walkhub/global/enums/Authority.java
Labels: 기능 추가

#38 🔀 :: (#25) ExerciseAnalysis 엔티티 생성
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/ExerciseAnalysis.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseAnalysisRepository.java
Labels: 기능 추가

#39 🔀 :: (#24) exercise entity
  src/main/java/com/walkhub/walkhub/WalkhubApplication.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseRepository.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/type/GoalType.java
  src/main/java/com/walkhub/walkhub/global/entity/BaseTimeEntity.java
Labels: 기능 추가

#42 🔀 :: (#23) challenge entity
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepository.java
Labels: 기능 추가

#43 🔀 :: (#27) certifying_shot entity
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/CertifyingShot.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/CertifyingShotRepository.java
Labels: 기능 추가

#41 🔀 :: (#28) location entity
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/Location.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/LocationId.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/LocationRepository.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationListId.java
Labels: 기능 추가

#45 26 challenge_status entity
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/ChallengeStatus.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/ChallengeStatusId.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepository.java
Labels: 기능 추가

#46 🔀 :: (#22) notice entity
  src/main/java/com/walkhub/walkhub/domain/notice/domain/Notice.java
  src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepository.java
  src/main/java/com/walkhub/walkhub/domain/notice/domain/type/Scope.java
Labels: 기능 추가

#49 🔀 :: (#48) global exception handler
  src/main/java/com/walkhub/walkhub/global/error/ErrorResponse.java
  src/main/java/com/walkhub/walkhub/global/error/GlobalExceptionHandler.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
  src/main/java/com/walkhub/walkhub/global/error/exception/WalkhubException.java
Labels: 기능 추가

#54 🔀 :: (#52) CI setting
  .github/workflows/Build.yml
  build.gradle
Labels: 프로젝트 설정

#53 🔀 :: (#50) security setting
  build.gradle
  src/main/java/com/walkhub/walkhub/WalkhubApplication.java
  src/main/java/com/walkhub/walkhub/domain/challenge/.gitkeep
  src/main/java/com/walkhub/walkhub/domain/exercise/.gitkeep
  src/main/java/com/walkhub/walkhub/domain/image/.gitkeep
  src/main/java/com/walkhub/walkhub/domain/notice/.gitkeep
  src/main/java/com/walkhub/walkhub/domain/notification/.gitkeep
  src/main/java/com/walkhub/walkhub/domain/teacher/.gitkeep
  src/main/java/com/walkhub/walkhub/domain/user/.gitkeep
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/exception/UserNotFoundException.java
  src/main/java/com/walkhub/walkhub/global/error/.gitkeep
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
  src/main/java/com/walkhub/walkhub/global/exception/ExpiredJwtException.java
  src/main/java/com/walkhub/walkhub/global/exception/InvalidJwtException.java
  src/main/java/com/walkhub/walkhub/global/security/.gitkeep
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
  src/main/java/com/walkhub/walkhub/global/security/auth/AuthDetails.java
  src/main/java/com/walkhub/walkhub/global/security/auth/AuthDetailsService.java
  src/main/java/com/walkhub/walkhub/global/security/jwt/JwtProperties.java
  src/main/java/com/walkhub/walkhub/global/security/jwt/JwtTokenFilter.java
  src/main/java/com/walkhub/walkhub/global/security/jwt/JwtTokenProvider.java
  src/main/resources/application.yml
Labels: 기능 추가

#58 🔀 :: (#55) 전화번호 인증 util
  build.gradle
  src/main/java/com/walkhub/walkhub/infrastructure/sms/SmsUtil.java
  src/main/java/com/walkhub/walkhub/infrastructure/sms/coolsms/CoolSms.java
  src/main/java/com/walkhub/walkhub/infrastructure/sms/coolsms/CoolSmsProperties.java
  src/main/resources/application.yml
Labels: 기능 추가

#59 🔀 :: (#56) 전화번호 인증(회원가입) API
  src/main/java/com/walkhub/walkhub/domain/teacher/domain/TeacherAuthCode.java
  src/main/java/com/walkhub/walkhub/domain/teacher/domain/repository/AuthCodeRepository.java
  src/main/java/com/walkhub/walkhub/domain/teacher/domain/repository/TeacherAuthCodeRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/UserAuthCode.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserAuthCodeRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserAuthCodeRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserAuthCodeService.java
  src/main/java/com/walkhub/walkhub/global/async/AsyncConfig.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
  src/main/java/com/walkhub/walkhub/global/web/WebMvcConfig.java
  src/main/java/com/walkhub/walkhub/infrastructure/sms/coolsms/CoolSms.java
  src/main/java/com/walkhub/walkhub/infrastructure/sms/coolsms/CoolSmsProperties.java
Labels: 기능 추가

#63 🔀 :: (#60) 사용자 로그인 API
  src/main/java/com/walkhub/walkhub/domain/auth/domain/RefreshToken.java
  src/main/java/com/walkhub/walkhub/domain/auth/domain/repository/RefreshTokenRepository.java
  src/main/java/com/walkhub/walkhub/domain/auth/exception/PasswordNotMatchException.java
  src/main/java/com/walkhub/walkhub/domain/auth/prsentation/AuthController.java
  src/main/java/com/walkhub/walkhub/domain/auth/prsentation/dto/request/SignInRequest.java
  src/main/java/com/walkhub/walkhub/domain/auth/prsentation/dto/response/UserTokenResponse.java
  src/main/java/com/walkhub/walkhub/domain/auth/service/UserSignInService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가

#64 🔀 :: (#62) 유저프로필 조회
  src/main/java/com/walkhub/walkhub/domain/user/facade/UserFacade.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/QueryUserProfileResponse.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java
Labels: 기능 추가

#69 🔀 :: (#57) user signup
  src/main/java/com/walkhub/walkhub/domain/user/exception/UnauthorizedUserAuthCodeException.java
  src/main/java/com/walkhub/walkhub/domain/user/exception/UserAuthCodeNotFoundException.java
  src/main/java/com/walkhub/walkhub/domain/user/exception/UserExistsException.java
  src/main/java/com/walkhub/walkhub/domain/user/facade/UserFacade.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserSignUpRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가

#67 🔀 :: (#65) 마이페이지 조회 api
  src/main/java/com/walkhub/walkhub/domain/user/facade/UserFacade.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/QueryMyPageResponse.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
  src/main/java/com/walkhub/walkhub/global/exception/CredentialsNotFoundException.java
  src/main/java/com/walkhub/walkhub/global/security/auth/AuthDetails.java
Labels: 기능 추가

#71 🔀 :: (#68) Refresh Token API
  src/main/java/com/walkhub/walkhub/domain/auth/domain/RefreshToken.java
  src/main/java/com/walkhub/walkhub/domain/auth/domain/repository/RefreshTokenRepository.java
  src/main/java/com/walkhub/walkhub/domain/auth/exception/RefreshTokenNotFoundException.java
  src/main/java/com/walkhub/walkhub/domain/auth/prsentation/AuthController.java
  src/main/java/com/walkhub/walkhub/domain/auth/prsentation/dto/response/UserAccessTokenResponse.java
  src/main/java/com/walkhub/walkhub/domain/auth/service/TokenRefreshService.java
  src/main/java/com/walkhub/walkhub/domain/auth/service/UserSignInService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
  src/main/java/com/walkhub/walkhub/global/security/jwt/JwtTokenProvider.java
Labels: 기능 추가

#77 🔀 :: (#66) 내 정보 수정 API
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/facade/UserFacade.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdateUserInfoRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UpdateUserInfoService.java
Labels: 기능 추가

#79 🔀 :: (#76) 챌린지 생성 API
  src/main/java/com/walkhub/walkhub/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presentation/dto/request/CreateChallengeRequest.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/CreateChallengeService.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 기능 추가

#81 🔀 :: (#80) auth 부분 prsentation -> presentation
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/AuthController.java
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/request/SignInRequest.java
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserTokenResponse.java
  src/main/java/com/walkhub/walkhub/domain/auth/prsentation/AuthController.java
  src/main/java/com/walkhub/walkhub/domain/auth/service/UserSignInService.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
Labels: 리팩토링

#88 🔀 :: 패키지명 오타 수정
  src/main/java/com/walkhub/walkhub/domain/auth/presentation/dto/response/UserAccessTokenResponse.java
  src/main/java/com/walkhub/walkhub/domain/auth/service/TokenRefreshService.java
Labels: 버그

#78 🔀 :: (#61) 건강 정보 입력 API
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/InputHealthInformationRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/InputHealthInformationService.java
Labels: 기능 추가

#84 🔀 :: (#73) Image Utility
  build.gradle
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
  src/main/java/com/walkhub/walkhub/global/exception/SaveImageFalseException.java
  src/main/java/com/walkhub/walkhub/infrastructure/image/ImageUtil.java
  src/main/java/com/walkhub/walkhub/infrastructure/image/s3/S3Facade.java
  src/main/java/com/walkhub/walkhub/infrastructure/image/s3/S3Properties.java
  src/main/java/com/walkhub/walkhub/infrastructure/s3/.gitkeep
  src/main/resources/application.yml
  src/test/java/com/walkhub/walkhub/IntegrationTest.java
Labels: 기능 추가

#83 🔀 :: (#70) fcm setting
  build.gradle
  src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationEntity.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationList.java
  src/main/java/com/walkhub/walkhub/domain/notification/domain/repository/NotificationRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/infrastructure/fcm/.gitkeep
  src/main/java/com/walkhub/walkhub/infrastructure/fcm/CoolNotification.java
  src/main/java/com/walkhub/walkhub/infrastructure/fcm/FcmUtil.java
  src/main/java/com/walkhub/walkhub/infrastructure/fcm/dto/SendDto.java
  src/main/resources/application.yml
Labels: 기능 추가

#96 🔀 :: (#95) SaveImageFalse ErrorCode 수정
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
  src/main/java/com/walkhub/walkhub/global/exception/SaveImageFalseException.java
Labels: chore

#94 🔀 :: (#92) Graceful shutdown 설정
  src/main/resources/application.yml
Labels: chore, 프로젝트 설정

#93 🔀 :: (#91) fcm initialize setting
  .gitignore
  src/main/java/com/walkhub/walkhub/domain/notification/domain/NotificationListId.java
  src/main/java/com/walkhub/walkhub/infrastructure/fcm/CoolNotification.java
  src/main/java/com/walkhub/walkhub/infrastructure/fcm/FcmUtil.java
Labels: 기능 추가

#102 🔀 :: (#99) Spring Batch 설정
  build.gradle
  src/main/java/com/walkhub/walkhub/WalkhubApplication.java
  src/main/resources/application.yml
Labels: 프로젝트 설정

#105 🔀 :: (#103) 기록 측정 시작(운동) api
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/Exercise.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/CreateExerciseRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/CreateExerciseResponse.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/CreateExerciseService.java
Labels: 기능 추가

#110 🔀 :: (#107) 챌린지 참여
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepository.java
  src/main/java/com/walkhub/walkhub/domain/challenge/exception/AlreadyParticipatedException.java
  src/main/java/com/walkhub/walkhub/domain/challenge/exception/ChallengeNotFoundException.java
  src/main/java/com/walkhub/walkhub/domain/challenge/exception/InvalidScopeException.java
  src/main/java/com/walkhub/walkhub/domain/challenge/facade/ChallengeFacade.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/ParticipateChallengeService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가

#113 🔀 :: (#100) 유저 조회하기 API
  src/main/java/com/walkhub/walkhub/domain/rank/.gitkeep
  src/main/java/com/walkhub/walkhub/domain/rank/domain/UserRank.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/UserRankRepository.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserListResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserSearchResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/UserSearchService.java
Labels: 기능 추가

#120 🔀 :: (#119) QueryDSL 세팅
  build.gradle
Labels: 프로젝트 설정

#118 🔀 :: (#116) 챌린지 참여자 목록보기
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepository.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presentation/dto/response/ChallengeParticipantsElement.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presentation/dto/response/ChallengeParticipantsListResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeParticipantsListService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
Labels: 기능 추가

#125 🔀 :: (#124) 챌린지 생성 Request @NotBlank -> @NotNull
  src/main/java/com/walkhub/walkhub/domain/challenge/presentation/dto/request/CreateChallengeRequest.java
Labels: chore, 리팩토링

#111 🔀 :: (#106) 공지사항 조회 api
  src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepository.java
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/NoticeController.java
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/response/QueryNoticeListResponse.java
  src/main/java/com/walkhub/walkhub/domain/notice/service/QueryNoticeListService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
  src/main/java/com/walkhub/walkhub/global/exception/InvalidRoleException.java
Labels: 기능 추가

#123 🔀 :: (#121) file upload
  src/main/java/com/walkhub/walkhub/domain/image/presentation/ImageController.java
  src/main/java/com/walkhub/walkhub/domain/image/presentation/dto/response/ImageUrlResponse.java
  src/main/java/com/walkhub/walkhub/domain/image/service/ImageUploadService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
  src/main/java/com/walkhub/walkhub/global/exception/SaveImageFailedException.java
  src/main/java/com/walkhub/walkhub/infrastructure/image/s3/S3Facade.java
Labels: 기능 추가, chore

#128 🔀 :: (#126) 반 가입하기
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/GroupId.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/exception/AlreadyJoinedException.java
  src/main/java/com/walkhub/walkhub/domain/user/exception/GroupNotFoundException.java
  src/main/java/com/walkhub/walkhub/domain/user/exception/InvalidClassCodeException.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/JoinGroupRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/JoinGroupService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가

#133 🔀 :: (#130) UserListResponse static class UserSearchResponse 추가
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserListResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/dto/response/UserSearchResponse.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/UserSearchService.java
Labels: chore, 리팩토링

#136 🔀 :: (#135) 유저 비밀번호 변경
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdatePasswordRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UpdatePasswordService.java
Labels: 기능 추가

#134 🔀 :: (#129) 운동 기록 측정 종료
  src/main/java/com/walkhub/walkhub/domain/exercise/exception/ExerciseNotFoundException.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/FinishExerciseRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/FinishExerciseService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가

#138 🔀 :: (#137) Docker Image Push
  Dockerfile
  build.gradle
Labels: 프로젝트 설정

#139 🔀 :: (#139) Build와 Push 분리
  .github/workflows/CD.yml
Labels: 버그

#141 🔀 :: (#140) javaSDK 의존성 수정
  build.gradle
Labels: chore

#147 🔀 :: (#146) @Digits -> @Column로 수정
  src/main/java/com/walkhub/walkhub/domain/user/domain/type/HealthInfo.java
Labels: 버그

#145 🔀 :: (#144) signup school name 추가
  src/main/java/com/walkhub/walkhub/domain/user/exception/SchoolNotFoundException.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UserSignUpRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가, chore

#148 🔀 :: (#142) 반 개설하기
  src/main/java/com/walkhub/walkhub/domain/teacher/exception/AlreadyCreatedException.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/request/CreateClassRequest.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/CreateClassResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/CreateClassService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserAuthCodeService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
  src/main/java/com/walkhub/walkhub/global/utils/code/RandomCodeUtil.java
Labels: 기능 추가

#150 🔀 :: (#117) modify school info
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/request/UpdateSchoolInfoRequest.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UpdateSchoolInfoService.java
Labels: 기능 추가

#151 🔀 :: (#143) 반 삭제하기
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/DeleteClassService.java
  src/main/java/com/walkhub/walkhub/domain/user/facade/UserFacade.java
  src/main/java/com/walkhub/walkhub/domain/user/service/JoinGroupService.java
Labels: 기능 추가

#154 🔀 :: (#152) teacher verification code
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/response/VerificationCodeResponse.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/CreateClassService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/VerificationCodeService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserAuthCodeService.java
  src/main/java/com/walkhub/walkhub/global/utils/code/RandomCodeUtil.java
Labels: 기능 추가

#158 🔀 :: (#157) delete notice
  src/main/java/com/walkhub/walkhub/domain/notice/exception/NoticeNotFoundException.java
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/NoticeController.java
  src/main/java/com/walkhub/walkhub/domain/notice/service/DeleteNoticeService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가

#156 🔀 :: (#155) 필드명 변경 image->imageUrl
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/Challenge.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/Badge.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/School.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/QueryMyPageResponse.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/QueryUserProfileResponse.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyPageService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryUserProfileService.java
Labels: 리팩토링

#170 🔀 :: (#169) 챌린지 조회 Dto 형식
  src/main/java/com/walkhub/walkhub/domain/challenge/presentation/dto/response/ChallengeParticipantsElement.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presentation/dto/response/ChallengeParticipantsListResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeParticipantsListService.java
Labels: 버그, 리팩토링

#159 🔀 :: (#153) 위치 저장하기
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/Location.java
  src/main/java/com/walkhub/walkhub/domain/exercise/facade/ExerciseFacade.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/ExerciseController.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/request/SaveLocationRequest.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/FinishExerciseService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/SaveLocationService.java
Labels: 기능 추가

#163 🔀 :: (#162) search user accountId
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/UserController.java
  src/main/java/com/walkhub/walkhub/domain/user/presentation/dto/response/UserAccountIdResponse.java
  src/main/java/com/walkhub/walkhub/domain/user/service/SearchAccountIdService.java
Labels: 기능 추가

#172 🔀 :: (#168) 챌린지 목록 보기 api
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepository.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presentation/ChallengeController.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presentation/dto/response/QueryChallengeListResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeListService.java
Labels: 기능 추가

#164 🔀 :: (#161) school logo image
  src/main/java/com/walkhub/walkhub/domain/school/exception/AgencyCodeNotMatchException.java
  src/main/java/com/walkhub/walkhub/domain/school/presentation/SchoolController.java
  src/main/java/com/walkhub/walkhub/domain/school/presentation/dto/request/SchoolLogoRequest.java
  src/main/java/com/walkhub/walkhub/domain/school/service/SchoolLogoSettingService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/School.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가

#181 🔀 :: (#180) User Entity & User Repository 파일 위치 변경
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepository.java
  src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepository.java
  src/main/java/com/walkhub/walkhub/domain/school/domain/School.java
  src/main/java/com/walkhub/walkhub/domain/school/domain/repository/SchoolRepository.java
  src/main/java/com/walkhub/walkhub/domain/school/service/SchoolLogoSettingService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/CreateClassService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/Group.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UpdateSchoolInfoService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
Labels: chore

#187 🔀 :: (#186) 토큰 필터 등록
  src/main/java/com/walkhub/walkhub/global/security/FilterConfig.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 기능 추가

#176 🔀 :: (#122) create notice
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/NoticeController.java
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/dto/request/CreateNoticeRequest.java
  src/main/java/com/walkhub/walkhub/domain/notice/service/CreateNoticeService.java
Labels: 기능 추가

#188 🔀 :: (#185) 랭크 뷰 수정
  src/main/java/com/walkhub/walkhub/domain/rank/domain/UserRankInfo.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/UserRankRepository.java
  src/main/java/com/walkhub/walkhub/domain/rank/presentation/RankController.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/UserSearchService.java
Labels: 기능 추가

#184 🔀 :: (#160) 학교 랭킹 저장하기
  src/main/java/com/walkhub/walkhub/WalkhubApplication.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRank.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRankInfo.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankInfoRepository.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
  src/main/java/com/walkhub/walkhub/domain/rank/job/SchoolRankJob.java
  src/main/java/com/walkhub/walkhub/domain/rank/scheduler/SchoolRankScheduler.java
  src/main/java/com/walkhub/walkhub/global/batch/UniqueIdGenerator.java
  src/main/resources/application.yml
Labels: 기능 추가

#192 🔀 :: (#191) JPAQueryFactory 빈 생성
  src/main/java/com/walkhub/walkhub/global/querydsl/QuerydslConfig.java
Labels: chore
