Repository Walkhub/Walkhub-Server, pull requests merged in 2022-05, with the labels that each got.

#703 🔀 :: (#702) 참여한 챌린지 목록 보기 500
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java
Labels: 버그

#708 🔀 :: (#706) 챌린지 목록 조회(앱) 쿼리
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeDetailsForStudentResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeDetailsForStudentService.java
Labels: 버그, chore

#715 🔀 :: (#711) 공지사항 보기 페이징 처리
  src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/notice/domain/repository/NoticeRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/notice/presentation/NoticeController.java
  src/main/java/com/walkhub/walkhub/domain/notice/service/QueryNoticeListService.java
Labels: chore

#716 🔀 :: (#714) 유저 검색 Api request에 validation option 추가
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/dto/request/UserSearchRequest.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/UserSearchForTeacherService.java
Labels: chore

#720 🔀 :: (#719) buildSortCondition 적용 안됨 오류 해결
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java
Labels: 버그, 리팩토링

#713 🔀 :: (#709) 챌린지 목록 보기(웹) resopnse
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeListForTeacherResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeListForTeacherService.java
Labels: 버그, chore

#712 🔀 :: (#710) 선생님 관리 Api
  src/main/java/com/walkhub/walkhub/domain/teacher/facade/TeacherFacade.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/ManageTeacherService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/QueryClassListService.java
Labels: chore

#721 🔀 :: (#718) 유저 상세조회 및 검색 시 운동 정보 null
  src/main/java/com/walkhub/walkhub/domain/exercise/facade/ExerciseAnalysisFacade.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseAnalysisService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/presentation/TeacherController.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/QueryUserDetailsService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/QueryUserListService.java
  src/main/java/com/walkhub/walkhub/domain/teacher/service/UserSearchForTeacherService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java
Labels: chore

#725 🔀 :: (#723) 중복전화번호 입력시 409 에러
  src/main/java/com/walkhub/walkhub/domain/auth/exception/PhoneNumberMatchedException.java
  src/main/java/com/walkhub/walkhub/domain/auth/service/CheckAuthCodeExistsService.java
  src/main/java/com/walkhub/walkhub/domain/user/facade/UserFacade.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UserSignUpService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가

#705 🔀 :: (#704) 엑셀 내보내기 Api 500
  src/main/java/com/walkhub/walkhub/domain/excel/domain/vo/UserInfoExcelVo.java
  src/main/java/com/walkhub/walkhub/domain/excel/presentation/ExcelController.java
  src/main/java/com/walkhub/walkhub/domain/excel/presentation/dto/request/PrintExcelRequest.java
  src/main/java/com/walkhub/walkhub/domain/excel/presentation/dto/request/UserInfoExcelRequest.java
  src/main/java/com/walkhub/walkhub/domain/excel/presentation/dto/response/PrintExcelResponse.java
  src/main/java/com/walkhub/walkhub/domain/excel/presentation/dto/response/UserInfoExcelResponse.java
  src/main/java/com/walkhub/walkhub/domain/excel/service/PrintExcelService.java
  src/main/java/com/walkhub/walkhub/domain/excel/service/UserInfoExcelService.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseAnalysisRepository.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseAnalysisRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseAnalysisRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/User.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/global/security/SecurityConfig.java
Labels: 버그, 리팩토링

#726 🔀 :: (#724) 반 가입시 중복 번호 error 처리
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepository.java
  src/main/java/com/walkhub/walkhub/domain/user/exception/AlreadyParticipatedNumberException.java
  src/main/java/com/walkhub/walkhub/domain/user/service/JoinSectionService.java
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
Labels: 기능 추가, 버그, chore

#731 🔀 :: (#730) 챌린지 참여 시 500 에러
  src/main/java/com/walkhub/walkhub/domain/challenge/service/ParticipateChallengeService.java
Labels: 버그

#732 🔀 :: (#678) 하루 운동 저장 API 수정
  src/main/java/com/walkhub/walkhub/domain/exercise/cache/ExerciseAnalysisCacheRepositoryImpl.java
Labels: 버그, 리팩토링

#729 🔀 :: (#728) objectMetadata 추가 & error 처리
  src/main/java/com/walkhub/walkhub/global/error/exception/ErrorCode.java
  src/main/java/com/walkhub/walkhub/global/exception/ImageValueNotFoundException.java
  src/main/java/com/walkhub/walkhub/infrastructure/image/s3/S3Facade.java
Labels: 리팩토링

#727 🔀 :: (#717) 챌린지 참여자 엑셀로 변환 API
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeStatusRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/vo/ChallengeDetailsForTeacherVO.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/request/ChallengeParticipantRequest.java
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeParticipantListResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeParticipantListService.java
  src/main/java/com/walkhub/walkhub/domain/excel/domain/type/UserType.java
  src/main/java/com/walkhub/walkhub/domain/excel/domain/vo/UserInfoExcelVo.java
  src/main/java/com/walkhub/walkhub/domain/excel/presentation/ExcelController.java
  src/main/java/com/walkhub/walkhub/domain/excel/presentation/dto/request/UserInfoExcelRequest.java
  src/main/java/com/walkhub/walkhub/domain/excel/presentation/dto/response/UserInfoExcelResponse.java
  src/main/java/com/walkhub/walkhub/domain/excel/service/UserInfoExcelService.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/user/domain/repository/UserRepositoryCustomImpl.java
Labels: 버그, 리팩토링

#734 🔀 :: (#733) 학교 상세보기 Api 500 해결
  src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRank.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/SchoolRankId.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
  src/main/java/com/walkhub/walkhub/domain/school/presentation/dto/response/SchoolDetailsInfoResponse.java
  src/main/java/com/walkhub/walkhub/domain/school/service/SchoolDetailsInfoService.java
Labels: 버그, 리팩토링

#736 🔀 :: (#735) 학교 랭킹 조회 및 검색 Api 500 해결
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepository.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/SchoolRankRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/SchoolSearchService.java
Labels: 버그, chore, 리팩토링

#741 🔀 :: (#740) 챌린지 참여자 목록 검색(웹) response 참여자 수 추가
  src/main/java/com/walkhub/walkhub/domain/challenge/presenstation/dto/response/QueryChallengeParticipantListResponse.java
  src/main/java/com/walkhub/walkhub/domain/challenge/service/QueryChallengeParticipantListService.java
Labels: chore

#745 🔀 :: (#744) 챌린지 목록 보기(앱) Api 500 해결
  src/main/java/com/walkhub/walkhub/domain/challenge/domain/repository/ChallengeRepositoryCustomImpl.java
Labels: 버그, chore, 리팩토링

#743 🔀 :: (#737) 운동 기록 보기(선생님용) 총 페이지 개수 추가
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/exercise/domain/repository/ExerciseRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/exercise/presentation/dto/response/QueryExerciseHistoryResponse.java
  src/main/java/com/walkhub/walkhub/domain/exercise/service/QueryExerciseHistoryService.java
Labels: 기능 추가, 버그

#749 🔀 :: (#748) 학교 변경 후 내 정보 보기 호출 시 school이 null로 뜸
  src/main/java/com/walkhub/walkhub/domain/user/service/QueryMyInformationService.java
  src/main/java/com/walkhub/walkhub/domain/user/service/UpdateUserInfoService.java
Labels: 버그

#752 🔀 :: (#750) 우리학교 유저 랭킹 조회 Api 500 해결
  src/main/java/com/walkhub/walkhub/domain/exercise/cache/ExerciseAnalysisCacheRepositoryImpl.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
Labels: 버그, chore, 리팩토링

#754 🔀 :: (#753) TodayRank이 null이면 ranking & walkCount 0처리
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
Labels: chore, 리팩토링

#756 🔀 :: (#755) [선생님] 유저 상세보기 API 응답값
  src/main/java/com/walkhub/walkhub/domain/exercise/facade/ExerciseAnalysisFacade.java
Labels: chore

#758 🔀 :: (#757) 우리학교 유저 랭킹 조회 Api 500해결
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/UserRankRepositoryCustom.java
  src/main/java/com/walkhub/walkhub/domain/rank/domain/repository/UserRankRepositoryCustomImpl.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListByMySchoolService.java
  src/main/java/com/walkhub/walkhub/domain/rank/service/QueryUserRankListService.java
Labels: 버그, chore, 리팩토링
